/* empty css                            */
import { c as createAstro, d as createComponent, r as renderTemplate, m as maybeRenderHead, e as addAttribute, i as renderTransition, h as renderComponent } from '../astro_Bq-bemsL.mjs';
import 'kleur/colors';
import 'html-escaper';
import { $ as $$MainLayout } from './contact_BrsQFEs5.mjs';
import 'clsx';
/* empty css                          */

const $$Astro$1 = createAstro();
const $$MainHOME = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro$1, $$props, $$slots);
  Astro2.self = $$MainHOME;
  return renderTemplate`${maybeRenderHead()}<div class="scroll-container" data-astro-cid-w6qpo335> <section class="hero-section" id="home" data-astro-cid-w6qpo335> <div class="hero-backdrop" aria-hidden="true" data-astro-cid-w6qpo335></div> <div class="section-content" data-astro-cid-w6qpo335> <div class="hero-text-wrapper" aria-label="Change yourself mantra" data-astro-cid-w6qpo335> <div class="hero-panel-grid" data-astro-cid-w6qpo335> <div class="hero-panel hero-panel--left slide-left" style="--panel-delay: 0s;" data-astro-cid-w6qpo335> <p class="hero-panel-text" data-astro-cid-w6qpo335>心が変われば行動が変わる。</p> </div> <div class="hero-panel hero-panel--right slide-right" style="--panel-delay: 0.15s;" data-astro-cid-w6qpo335> <p class="hero-panel-text" data-astro-cid-w6qpo335>行動が変われば習慣が変わる。</p> </div> <div class="hero-panel hero-panel--left slide-left" style="--panel-delay: 0.3s;" data-astro-cid-w6qpo335> <p class="hero-panel-text" data-astro-cid-w6qpo335>習慣が変われば人格が変わる。</p> </div> <div class="hero-panel hero-panel--right slide-right" style="--panel-delay: 0.45s;" data-astro-cid-w6qpo335> <p class="hero-panel-text" data-astro-cid-w6qpo335>人格が変われば運命が変わる。</p> </div> <div class="hero-panel hero-panel--full slide-bottom" style="--panel-delay: 0.75s;" data-astro-cid-w6qpo335> <h1 class="hero-headline hero-main-title" data-astro-cid-w6qpo335>Change yourself.</h1> </div> </div> </div> </div> </section> <section class="app-detail-section" id="riddle" data-theme="riddle" data-astro-cid-w6qpo335> <div class="section-content" data-astro-cid-w6qpo335> <div class="app-detail-content" data-astro-cid-w6qpo335> <div class="app-info-left" data-astro-cid-w6qpo335> <span class="app-pill" data-astro-cid-w6qpo335>クイズ✖️SNS</span> <img src="/RiddleLogo.png" class="app-logo" alt="Riddle App Logo" data-astro-cid-w6qpo335${addAttribute(renderTransition($$result, "i3r2dcdq", "", "riddle"), "data-astro-transition-scope")}> <h2 class="app-name" data-astro-cid-w6qpo335>Riddle</h2> <p class="app-tagline" data-astro-cid-w6qpo335>Change your thinking.</p> </div> <div class="app-info-right" data-astro-cid-w6qpo335> <p class="app-description" data-astro-cid-w6qpo335>
クイズ✖️SNSで思考力とつながりを同時にアップデート。難問に挑戦しながら、コミュニティで解法や気づきをシェアできます。
</p> <div class="app-features" data-astro-cid-w6qpo335> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>🧩</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>豊富なパズルコレクション</p> <p class="feature-description" data-astro-cid-w6qpo335>論理、数学、言葉など多彩なジャンルに挑戦できます。</p> </div> </div> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>🎯</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>段階的な難易度設計</p> <p class="feature-description" data-astro-cid-w6qpo335>初心者から上級者まで、自分に合ったレベルで継続的にステップアップ。</p> </div> </div> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>📊</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>進捗追跡機能</p> <p class="feature-description" data-astro-cid-w6qpo335>プレイ履歴を可視化して、学習効果と成長を確認できます。</p> </div> </div> </div> <div class="app-actions" data-astro-cid-w6qpo335> <div class="app-links" data-astro-cid-w6qpo335> <a href="/riddle" class="cta-button surface" aria-label="Riddleアプリの詳細を見る" data-astro-cid-w6qpo335> <span class="cta-icon" data-astro-cid-w6qpo335>🧩</span>アプリ詳細を見る
</a> <span class="app-availability" data-astro-cid-w6qpo335>iOS / Android 対応</span> </div> <div class="store-buttons" data-astro-cid-w6qpo335> <a href="https://apps.apple.com/jp/app/riddle/id1621658101" class="store-button store-button--app-store" target="_blank" rel="noopener noreferrer" data-astro-cid-w6qpo335> <img src="/Download_on_the_App_Store_Badge_JP_RGB_blk_100317.svg" alt="App Storeでダウンロード" class="store-badge" loading="lazy" data-astro-cid-w6qpo335> </a> <a href="https://play.google.com/store/apps/details?id=com.higuchiyuya.riddle" class="store-button store-button--google" target="_blank" rel="noopener noreferrer" data-astro-cid-w6qpo335> <img src="/Riddle/GetItOnGooglePlay_Badge_Web_color_Japanese.png" alt="Google Playで入手" class="store-badge" loading="lazy" data-astro-cid-w6qpo335> </a> </div> </div> </div> </div> </div> </section> <section class="app-detail-section" id="prompty" data-theme="prompty" data-astro-cid-w6qpo335> <div class="section-content" data-astro-cid-w6qpo335> <div class="app-detail-content" data-astro-cid-w6qpo335> <div class="app-info-left" data-astro-cid-w6qpo335> <span class="app-pill" data-astro-cid-w6qpo335>promptを生成・共有</span> <img src="/Prompty/icon_removebg-preview.png" class="app-logo" alt="Prompty App Logo" data-astro-cid-w6qpo335> <h2 class="app-name" data-astro-cid-w6qpo335>Prompty</h2> <p class="app-tagline" data-astro-cid-w6qpo335>Change your prompt.</p> </div> <div class="app-info-right" data-astro-cid-w6qpo335> <p class="app-description" data-astro-cid-w6qpo335>
promptを生成・共有する新しいワークスペース。AIに響くプロンプトを作り、コミュニティで磨きながら成果を加速させましょう。
</p> <div class="app-features" data-astro-cid-w6qpo335> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>✨</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>AI最適化プロンプト</p> <p class="feature-description" data-astro-cid-w6qpo335>生成AIが理解しやすい形に整えた高品質なプロンプトを即座に生成します。</p> </div> </div> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>🎨</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>創造性支援機能</p> <p class="feature-description" data-astro-cid-w6qpo335>インスピレーションを刺激するサンプルとヒントでアイデア出しをサポートします。</p> </div> </div> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>💡</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>テンプレートギャラリー</p> <p class="feature-description" data-astro-cid-w6qpo335>ビジネスや学習などのシーン別テンプレートを多数収録しています。</p> </div> </div> </div> <div class="app-actions" data-astro-cid-w6qpo335> <div class="app-links" data-astro-cid-w6qpo335> <a href="/prompty" class="cta-button surface" aria-label="Promptyアプリの詳細を見る" data-astro-cid-w6qpo335> <span class="cta-icon" data-astro-cid-w6qpo335>✨</span>アプリ詳細を見る
</a> <span class="app-availability" data-astro-cid-w6qpo335>Android 先行提供</span> </div> <div class="store-buttons" data-astro-cid-w6qpo335> <span class="store-button store-button--app-store disabled" aria-disabled="true" data-astro-cid-w6qpo335> <img src="/Download_on_the_App_Store_Badge_JP_RGB_blk_100317.svg" alt="App Store版は近日公開予定" class="store-badge" loading="lazy" data-astro-cid-w6qpo335> </span> <a href="https://play.google.com/store/apps/details?id=com.hero.prompty" class="store-button store-button--google" target="_blank" rel="noopener noreferrer" data-astro-cid-w6qpo335> <img src="/Riddle/GetItOnGooglePlay_Badge_Web_color_Japanese.png" alt="Google Playで入手" class="store-badge" loading="lazy" data-astro-cid-w6qpo335> </a> </div> <p class="store-note" data-astro-cid-w6qpo335>※ App Store版は現在準備中です。公開時にこちらでお知らせします。</p> </div> </div> </div> </div> </section> <section class="app-detail-section" id="summaries" data-theme="summaries" data-astro-cid-w6qpo335> <div class="section-content" data-astro-cid-w6qpo335> <div class="app-detail-content" data-astro-cid-w6qpo335> <div class="app-info-left" data-astro-cid-w6qpo335> <span class="app-pill" data-astro-cid-w6qpo335>要約✖️SNS</span> <img src="/SummariesLogo.png" class="app-logo" alt="Summaries App Logo" data-astro-cid-w6qpo335> <h2 class="app-name" data-astro-cid-w6qpo335>Summaries</h2> <p class="app-tagline" data-astro-cid-w6qpo335>Change your reading.</p> </div> <div class="app-info-right" data-astro-cid-w6qpo335> <p class="app-description" data-astro-cid-w6qpo335>
要約✖️SNSで情報共有のスピードを刷新。AI要約で要点を押さえ、仲間と知識を交換しながら学びを深めます。
</p> <div class="app-features" data-astro-cid-w6qpo335> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>📚</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>AI要約エンジン</p> <p class="feature-description" data-astro-cid-w6qpo335>高度な自然言語処理で重要なポイントだけを抽出します。</p> </div> </div> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>⚡</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>高速処理</p> <p class="feature-description" data-astro-cid-w6qpo335>長文のドキュメントでも数秒で要約し、時間を有効に活用できます。</p> </div> </div> <div class="feature-item" data-astro-cid-w6qpo335> <span class="feature-icon" data-astro-cid-w6qpo335>🎯</span> <div data-astro-cid-w6qpo335> <p class="feature-title" data-astro-cid-w6qpo335>カスタム要約</p> <p class="feature-description" data-astro-cid-w6qpo335>必要な情報量に合わせて、要約の長さや粒度を柔軟に調整できます。</p> </div> </div> </div> <div class="app-actions" data-astro-cid-w6qpo335> <div class="app-links" data-astro-cid-w6qpo335> <a href="/summaries_app_description" class="cta-button surface" aria-label="Summariesアプリの詳細を見る" data-astro-cid-w6qpo335> <span class="cta-icon" data-astro-cid-w6qpo335>📚</span>アプリ詳細を見る
</a> <span class="app-availability" data-astro-cid-w6qpo335>Coming soon</span> </div> </div> </div> </div> </div> </section> <section class="contact-section" id="contact" data-astro-cid-w6qpo335> <div class="section-content" data-astro-cid-w6qpo335> <div class="contact-card" data-astro-cid-w6qpo335> <h2 class="contact-title" data-astro-cid-w6qpo335>お問い合わせ</h2> <p class="contact-description" data-astro-cid-w6qpo335>
ご質問や導入のご相談がありましたら、お気軽にお知らせください。専門チームが迅速にサポートいたします。
</p> <div class="contact-actions" data-astro-cid-w6qpo335> <a href="/contact" class="cta-button primary" aria-label="お問い合わせフォームへ" data-astro-cid-w6qpo335> <span class="cta-icon" data-astro-cid-w6qpo335>💬</span>お問い合わせフォーム
</a> <a href="mailto:higuchiyuya.prompty@gmail.com" class="cta-button secondary" aria-label="メールで問い合わせる" data-astro-cid-w6qpo335> <span class="cta-icon" data-astro-cid-w6qpo335>✉️</span>メールで相談する
</a> </div> </div> </div> </section> </div> `;
}, "/home/user/hero-hp/src/components/Main_HOME.astro", "self");

const $$Astro = createAstro();
const $$Index = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Index;
  return renderTemplate`${renderComponent($$result, "MainLayout", $$MainLayout, { "title": "He-ro", "lang": "ja", "variant": "dark" }, { "default": ($$result2) => renderTemplate` ${renderComponent($$result2, "Main_HOME", $$MainHOME, {})} ` })}`;
}, "/home/user/hero-hp/src/pages/index.astro", void 0);

const $$file = "/home/user/hero-hp/src/pages/index.astro";
const $$url = "";

export { $$Index as default, $$file as file, $$url as url };
